#!/usr/bin/env node
/**
 * generate.mjs — Use big-pickle (opencode.ai) to turn data/history.json into
 * a beautiful, self-contained dashboard (index.html) with tables showing each
 * game and its daily requests.
 *
 * Env: OPENCODE_API_KEY (GitHub Actions secret)
 *
 * Robustness: the model output is validated (must contain </html>, reasonable
 * size). If it fails, a deterministic fallback dashboard is generated so the
 * pipeline NEVER breaks the site.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const HISTORY_FILE = path.join(ROOT, "data", "history.json");
const OUT_FILE = path.join(ROOT, "index.html");

const API_URL = "https://opencode.ai/zen/v1/chat/completions";
const MODEL = "big-pickle";

// ── Load + summarize history ────────────────────────────────────────────────
function summarize(history) {
  // Flatten: list of { account, accountLabel, service, platform, kind, daily }
  const out = [];
  for (const [accId, acc] of Object.entries(history.accounts || {})) {
    for (const svc of Object.values(acc.services || {})) {
      out.push({
        account: acc.label || accId,
        service: svc.name,
        platform: svc.platform || "worker",
        kind: svc.kind || "worker",
        daily: svc.daily || {},
      });
    }
  }
  out.sort((a, b) => {
    const aTot = Object.values(a.daily).reduce((s, v) => s + v, 0);
    const bTot = Object.values(b.daily).reduce((s, v) => s + v, 0);
    return bTot - aTot;
  });
  return { updatedAt: history.updatedAt, services: out };
}

// ── big-pickle call ─────────────────────────────────────────────────────────
async function generateWithModel(summary) {
  const apiKey = process.env.OPENCODE_API_KEY;
  if (!apiKey) throw new Error("OPENCODE_API_KEY not set");

  const prompt = `You are the data-visualization engine for a statistics dashboard tracking daily Cloudflare request counts for our games and services.

Here is the data (JSON): ${JSON.stringify(summary)}

Create a COMPLETE, standalone, modern dark-themed dashboard as a single HTML file. Requirements:
1. Title: "Game Statistics Dashboard" with a game controller emoji 🎮.
2. A summary "at a glance" row of stat cards: total requests (all services, last day), total requests (all services, all time shown), number of services tracked, and the top service by total requests.
3. A main table with columns: Service | Account | Platform | Requests per day (one column per date present in the data, newest last) | Total | Trend (▲/▼ vs previous day where data exists).
4. Highlight game services (kind contains "game" OR service names matching known games like trivia, bible, quran, dice, bluff, snake, pop, casino, voice, youtrivia) with a 🎮 emoji and a subtle gold background. Non-games (opencode-proxy, audiobooks, youstream-proxy, wstest-probe2, etc.) shown dimmed/grayed as "infrastructure".
5. A horizontal bar chart (pure CSS divs, no external libraries) ranking services by total requests.
6. A "Trending" section calling out the top 3 services with the biggest request growth (or least decline) between the two most recent days with data.
7. Footer: "Generated by big-pickle · <updatedAt> · Data: Cloudflare GraphQL Analytics".
8. Self-contained: ALL CSS inline in a <style> tag. No external fonts, no JS frameworks, no CDN links. Small vanilla JS allowed for sorting but keep minimal.
9. Use a modern dark palette (deep navy/emerald background, gold accents — fitting a gaming brand), clean typography, responsive table with horizontal scroll on small screens.
10. Format numbers with thousands separators.
11. If there is no data at all, show a friendly "No data collected yet" message.

Return ONLY the complete HTML document (starting with <!DOCTYPE html>). Do not wrap in markdown code fences. Do not add any text outside the HTML.`;

  const res = await fetch(API_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({
      model: MODEL,
      messages: [
        {
          role: "system",
          content:
            "You are a senior front-end developer who writes beautiful, self-contained HTML dashboards. Always respond with valid HTML only — no markdown, no extra text.",
        },
        { role: "user", content: prompt },
      ],
      temperature: 0.4,
      max_tokens: 32000,
    }),
  });

  if (!res.ok) throw new Error(`opencode.ai ${res.status}: ${(await res.text()).slice(0, 200)}`);
  const data = await res.json();
  let content = data?.choices?.[0]?.message?.content || "";
  const reasoning = data?.choices?.[0]?.message?.reasoning_content || "";
  if (!content.trim()) {
    // Diagnostic: log the raw response shape so Actions logs show what came back
    console.error(
      `[generate] empty content — reasoning_len=${String(reasoning).length}, finish=${data?.choices?.[0]?.finish_reason}, raw: ${JSON.stringify(data).slice(0, 400)}`
    );
    throw new Error("empty model response");
  }
  content = content.replace(/```html\n?/gi, "").replace(/```\n?/g, "").trim();
  if (!/<\/html>/i.test(content)) throw new Error("model output missing </html>");
  if (content.length > 1_500_000) throw new Error("model output too large");
  return content;
}

// ── Deterministic fallback dashboard ────────────────────────────────────────
function fallbackDashboard(summary) {
  const fmt = (n) => Number(n || 0).toLocaleString("en-US");
  const dates = new Set();
  for (const s of summary.services) for (const d of Object.keys(s.daily)) dates.add(d);
  const sortedDates = [...dates].sort();
  const lastDate = sortedDates[sortedDates.length - 1] || "";
  const prevDate = sortedDates[sortedDates.length - 2] || "";
  const totalAll = summary.services.reduce(
    (t, s) => t + Object.values(s.daily).reduce((a, b) => a + b, 0),
    0
  );
  const lastDayTotal = summary.services.reduce((t, s) => t + (s.daily[lastDate] || 0), 0);

  const isGame = (s) => /game|trivia|bible|quran|dice|bluff|snake|pop|casino|voice|youtrivia|arrow|hindsight/i.test(`${s.kind} ${s.service}`);

  const rows = summary.services
    .map((s) => {
      const cells = sortedDates.map((d) => `<td>${fmt(s.daily[d] || 0)}</td>`).join("");
      const total = Object.values(s.daily).reduce((a, b) => a + b, 0);
      const trend =
        lastDate && prevDate
          ? (s.daily[lastDate] || 0) >= (s.daily[prevDate] || 0)
            ? '<span style="color:#3ecf8e">▲</span>'
            : '<span style="color:#ff6b6b">▼</span>'
          : "—";
      const max = Math.max(1, ...summary.services.map((x) => Object.values(x.daily).reduce((a, b) => a + b, 0)));
      const bar = (total / max) * 100;
      const cls = isGame(s) ? "game" : "infra";
      return `<tr class="${cls}">
        <td class="svc">${isGame(s) ? "🎮 " : "🛠️ "}${s.service}</td>
        <td>${s.account}</td>
        <td><span class="plat">${s.platform}</span></td>
        ${cells}
        <td class="total">${fmt(total)}</td>
        <td>${trend}</td>
        <td class="bar-cell"><div class="bar" style="width:${bar.toFixed(1)}%"></div></td>
      </tr>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>🎮 Game Statistics Dashboard</title>
<style>
:root { --bg:#081c14; --card:#122b20; --card2:#183829; --border:#1f4a35; --text:#eef1fb; --muted:#93b8a8; --gold:#e8c468; --green:#3ecf8e; --red:#ff6b6b; }
* { box-sizing:border-box; margin:0; padding:0; }
body { background:radial-gradient(1200px 600px at 50% -10%, #0f4a2e 0%, var(--bg) 55%) fixed, var(--bg); color:var(--text); font-family:"Segoe UI", system-ui, sans-serif; padding:24px; }
h1 { font-size:26px; margin-bottom:4px; }
.sub { color:var(--muted); font-size:13px; margin-bottom:20px; }
.cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:14px; margin-bottom:24px; }
.card { background:var(--card); border:1px solid var(--border); border-radius:14px; padding:16px; }
.card .label { color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:.5px; }
.card .value { font-size:24px; font-weight:700; margin-top:6px; color:var(--gold); }
.table-wrap { overflow-x:auto; background:var(--card); border:1px solid var(--border); border-radius:14px; }
table { border-collapse:collapse; width:100%; font-size:13px; min-width:900px; }
th, td { padding:9px 12px; text-align:right; border-bottom:1px solid var(--border); white-space:nowrap; }
th { color:var(--muted); font-size:11px; text-transform:uppercase; letter-spacing:.5px; background:var(--card2); position:sticky; top:0; }
td:first-child, th:first-child { text-align:left; }
td.svc { font-weight:600; }
tr.game { background:rgba(232,196,104,.05); }
tr.game td.svc { color:var(--gold); }
tr.infra td { opacity:.55; }
td.total { font-weight:700; color:var(--gold); }
.plat { background:var(--card2); border:1px solid var(--border); border-radius:20px; padding:2px 8px; font-size:11px; color:var(--muted); }
.bar-cell { width:160px; }
.bar { height:10px; background:linear-gradient(90deg, var(--gold), #f5dfa0); border-radius:6px; margin-left:auto; }
footer { margin-top:20px; color:var(--muted); font-size:12px; text-align:center; }
</style>
</head>
<body>
<h1>🎮 Game Statistics Dashboard</h1>
<p class="sub">Daily Cloudflare request counts · Workers + Pages · both accounts</p>
<div class="cards">
  <div class="card"><div class="label">Requests (last day: ${lastDate || "—"})</div><div class="value">${fmt(lastDayTotal)}</div></div>
  <div class="card"><div class="label">Total requests (all time)</div><div class="value">${fmt(totalAll)}</div></div>
  <div class="card"><div class="label">Services tracked</div><div class="value">${summary.services.length}</div></div>
  <div class="card"><div class="label">Updated</div><div class="value" style="font-size:15px">${(summary.updatedAt || "—").slice(0, 16)}</div></div>
</div>
<div class="table-wrap">
<table>
<thead><tr><th>Service</th><th>Account</th><th>Platform</th>${sortedDates.map((d) => `<th>${d.slice(5)}</th>`).join("")}<th>Total</th><th>Trend</th><th>Share</th></tr></thead>
<tbody>${rows}</tbody>
</table>
</div>
<footer>Generated by big-pickle · ${summary.updatedAt || ""} · Data: Cloudflare GraphQL Analytics</footer>
</body>
</html>`;
}

// ── Main ────────────────────────────────────────────────────────────────────
if (!fs.existsSync(HISTORY_FILE)) {
  console.error("data/history.json missing — run collect.mjs first");
  process.exit(1);
}
const history = JSON.parse(fs.readFileSync(HISTORY_FILE, "utf8"));
const summary = summarize(history);

let html = null;
let lastErr = null;
for (let attempt = 1; attempt <= 3 && !html; attempt++) {
  try {
    console.log(`Calling big-pickle to build the dashboard (attempt ${attempt})…`);
    html = await generateWithModel(summary);
    console.log(`Model output OK (${html.length.toLocaleString()} chars)`);
  } catch (err) {
    lastErr = err;
    console.warn(`Model attempt ${attempt} failed: ${err.message}`);
    if (attempt < 3) await new Promise((r) => setTimeout(r, 15000 * attempt));
  }
}
if (!html) {
  console.warn("Model failed all attempts, using fallback:", lastErr?.message);
  html = fallbackDashboard(summary);
}

fs.writeFileSync(OUT_FILE, html);
console.log(`✅ index.html written (${html.length.toLocaleString()} chars)`);
